.TH "Attitude" 3 "Bus et Réseaux - VO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Attitude
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBr\fP"
.br
.ti -1c
.RI "float \fBp\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB70\fP of file \fBMPU9250_driver\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "float p"

.PP
Definition at line \fB72\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "float r"

.PP
Definition at line \fB72\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "float y"

.PP
Definition at line \fB72\fP of file \fBMPU9250_driver\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bus et Réseaux - VO from the source code\&.
