.TH "/home/oliver/Documents/3A/capteurs_reseaux_VO_ESE_TP2/capteurs_reseaux_VO/Core/Inc/gpio.h" 3 "Bus et Réseaux - VO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/oliver/Documents/3A/capteurs_reseaux_VO_ESE_TP2/capteurs_reseaux_VO/Core/Inc/gpio.h \- This file contains all the function prototypes for the \fBgpio\&.c\fP file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_GPIO_Init\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains all the function prototypes for the \fBgpio\&.c\fP file\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2024 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.PP
Definition in file \fBgpio\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void MX_GPIO_Init (void)"
Configure pins as Analog Input Output EVENT_OUT EXTI 
.PP
Definition at line \fB42\fP of file \fBgpio\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bus et Réseaux - VO from the source code\&.
