.TH "GyroCal" 3 "Bus et Réseaux - VO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GyroCal
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB65\fP of file \fBMPU9250_driver\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "float x"

.PP
Definition at line \fB67\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "float y"

.PP
Definition at line \fB67\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "float z"

.PP
Definition at line \fB67\fP of file \fBMPU9250_driver\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bus et Réseaux - VO from the source code\&.
