.TH "/home/oliver/Documents/3A/capteurs_reseaux_VO_ESE_TP2/capteurs_reseaux_VO/Core/Inc/main.h" 3 "Version TP5" "Bus et Réseaux - VO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/oliver/Documents/3A/capteurs_reseaux_VO_ESE_TP2/capteurs_reseaux_VO/Core/Inc/main.h \- : Header for \fBmain\&.c\fP file\&. This file contains the common defines of the application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBB1_Pin\fP   GPIO_PIN_13"
.br
.ti -1c
.RI "#define \fBB1_GPIO_Port\fP   GPIOC"
.br
.ti -1c
.RI "#define \fBUSART_TX_Pin\fP   GPIO_PIN_2"
.br
.ti -1c
.RI "#define \fBUSART_TX_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBUSART_RX_Pin\fP   GPIO_PIN_3"
.br
.ti -1c
.RI "#define \fBUSART_RX_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBLD2_Pin\fP   GPIO_PIN_5"
.br
.ti -1c
.RI "#define \fBLD2_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBTMS_Pin\fP   GPIO_PIN_13"
.br
.ti -1c
.RI "#define \fBTMS_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBTCK_Pin\fP   GPIO_PIN_14"
.br
.ti -1c
.RI "#define \fBTCK_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBSWO_Pin\fP   GPIO_PIN_3"
.br
.ti -1c
.RI "#define \fBSWO_GPIO_Port\fP   GPIOB"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBError_Handler\fP (void)"
.br
.RI "This function is executed in case of error occurrence\&. "
.in -1c
.SH "Detailed Description"
.PP 
: Header for \fBmain\&.c\fP file\&. This file contains the common defines of the application\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2024 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.PP
Definition in file \fBmain\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define B1_GPIO_Port   GPIOC"

.PP
Definition at line \fB61\fP of file \fBmain\&.h\fP\&.
.SS "#define B1_Pin   GPIO_PIN_13"

.PP
Definition at line \fB60\fP of file \fBmain\&.h\fP\&.
.SS "#define LD2_GPIO_Port   GPIOA"

.PP
Definition at line \fB67\fP of file \fBmain\&.h\fP\&.
.SS "#define LD2_Pin   GPIO_PIN_5"

.PP
Definition at line \fB66\fP of file \fBmain\&.h\fP\&.
.SS "#define SWO_GPIO_Port   GPIOB"

.PP
Definition at line \fB73\fP of file \fBmain\&.h\fP\&.
.SS "#define SWO_Pin   GPIO_PIN_3"

.PP
Definition at line \fB72\fP of file \fBmain\&.h\fP\&.
.SS "#define TCK_GPIO_Port   GPIOA"

.PP
Definition at line \fB71\fP of file \fBmain\&.h\fP\&.
.SS "#define TCK_Pin   GPIO_PIN_14"

.PP
Definition at line \fB70\fP of file \fBmain\&.h\fP\&.
.SS "#define TMS_GPIO_Port   GPIOA"

.PP
Definition at line \fB69\fP of file \fBmain\&.h\fP\&.
.SS "#define TMS_Pin   GPIO_PIN_13"

.PP
Definition at line \fB68\fP of file \fBmain\&.h\fP\&.
.SS "#define USART_RX_GPIO_Port   GPIOA"

.PP
Definition at line \fB65\fP of file \fBmain\&.h\fP\&.
.SS "#define USART_RX_Pin   GPIO_PIN_3"

.PP
Definition at line \fB64\fP of file \fBmain\&.h\fP\&.
.SS "#define USART_TX_GPIO_Port   GPIOA"

.PP
Definition at line \fB63\fP of file \fBmain\&.h\fP\&.
.SS "#define USART_TX_Pin   GPIO_PIN_2"

.PP
Definition at line \fB62\fP of file \fBmain\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void Error_Handler (void)"

.PP
This function is executed in case of error occurrence\&. 
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line \fB322\fP of file \fBmain\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bus et Réseaux - VO from the source code\&.
