.TH "RawData" 3 "Version TP5" "Bus et Réseaux - VO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RawData
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBax\fP"
.br
.ti -1c
.RI "int16_t \fBay\fP"
.br
.ti -1c
.RI "int16_t \fBaz\fP"
.br
.ti -1c
.RI "int16_t \fBgx\fP"
.br
.ti -1c
.RI "int16_t \fBgy\fP"
.br
.ti -1c
.RI "int16_t \fBgz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB55\fP of file \fBMPU9250_driver\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int16_t ax"

.PP
Definition at line \fB57\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "int16_t ay"

.PP
Definition at line \fB57\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "int16_t az"

.PP
Definition at line \fB57\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "int16_t gx"

.PP
Definition at line \fB57\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "int16_t gy"

.PP
Definition at line \fB57\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "int16_t gz"

.PP
Definition at line \fB57\fP of file \fBMPU9250_driver\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bus et Réseaux - VO from the source code\&.
