.TH "SensorData" 3 "Bus et Réseaux - VO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SensorData
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBax\fP"
.br
.ti -1c
.RI "float \fBay\fP"
.br
.ti -1c
.RI "float \fBaz\fP"
.br
.ti -1c
.RI "float \fBgx\fP"
.br
.ti -1c
.RI "float \fBgy\fP"
.br
.ti -1c
.RI "float \fBgz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB60\fP of file \fBMPU9250_driver\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "float ax"

.PP
Definition at line \fB62\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "float ay"

.PP
Definition at line \fB62\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "float az"

.PP
Definition at line \fB62\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "float gx"

.PP
Definition at line \fB62\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "float gy"

.PP
Definition at line \fB62\fP of file \fBMPU9250_driver\&.h\fP\&.
.SS "float gz"

.PP
Definition at line \fB62\fP of file \fBMPU9250_driver\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bus et Réseaux - VO from the source code\&.
