.TH "/home/oliver/Documents/3A/capteurs_reseaux_VO_ESE_TP2/capteurs_reseaux_VO/Core/Src/stm32f4xx_it.c" 3 "Bus et Réseaux - VO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/oliver/Documents/3A/capteurs_reseaux_VO_ESE_TP2/capteurs_reseaux_VO/Core/Src/stm32f4xx_it.c \- Interrupt Service Routines\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'stm32f4xx_it\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBNMI_Handler\fP (void)"
.br
.RI "This function handles Non maskable interrupt\&. "
.ti -1c
.RI "void \fBHardFault_Handler\fP (void)"
.br
.RI "This function handles Hard fault interrupt\&. "
.ti -1c
.RI "void \fBMemManage_Handler\fP (void)"
.br
.RI "This function handles Memory management fault\&. "
.ti -1c
.RI "void \fBBusFault_Handler\fP (void)"
.br
.RI "This function handles Pre-fetch fault, memory access fault\&. "
.ti -1c
.RI "void \fBUsageFault_Handler\fP (void)"
.br
.RI "This function handles Undefined instruction or illegal state\&. "
.ti -1c
.RI "void \fBSVC_Handler\fP (void)"
.br
.RI "This function handles System service call via SWI instruction\&. "
.ti -1c
.RI "void \fBDebugMon_Handler\fP (void)"
.br
.RI "This function handles Debug monitor\&. "
.ti -1c
.RI "void \fBPendSV_Handler\fP (void)"
.br
.RI "This function handles Pendable request for system service\&. "
.ti -1c
.RI "void \fBSysTick_Handler\fP (void)"
.br
.RI "This function handles System tick timer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interrupt Service Routines\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2024 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.PP
Definition in file \fBstm32f4xx_it\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void BusFault_Handler (void)"

.PP
This function handles Pre-fetch fault, memory access fault\&. 
.PP
Definition at line \fB114\fP of file \fBstm32f4xx_it\&.c\fP\&.
.SS "void DebugMon_Handler (void)"

.PP
This function handles Debug monitor\&. 
.PP
Definition at line \fB157\fP of file \fBstm32f4xx_it\&.c\fP\&.
.SS "void HardFault_Handler (void)"

.PP
This function handles Hard fault interrupt\&. 
.PP
Definition at line \fB84\fP of file \fBstm32f4xx_it\&.c\fP\&.
.SS "void MemManage_Handler (void)"

.PP
This function handles Memory management fault\&. 
.PP
Definition at line \fB99\fP of file \fBstm32f4xx_it\&.c\fP\&.
.SS "void NMI_Handler (void)"

.PP
This function handles Non maskable interrupt\&. 
.PP
Definition at line \fB69\fP of file \fBstm32f4xx_it\&.c\fP\&.
.SS "void PendSV_Handler (void)"

.PP
This function handles Pendable request for system service\&. 
.PP
Definition at line \fB170\fP of file \fBstm32f4xx_it\&.c\fP\&.
.SS "void SVC_Handler (void)"

.PP
This function handles System service call via SWI instruction\&. 
.PP
Definition at line \fB144\fP of file \fBstm32f4xx_it\&.c\fP\&.
.SS "void SysTick_Handler (void)"

.PP
This function handles System tick timer\&. 
.PP
Definition at line \fB183\fP of file \fBstm32f4xx_it\&.c\fP\&.
.SS "void UsageFault_Handler (void)"

.PP
This function handles Undefined instruction or illegal state\&. 
.PP
Definition at line \fB129\fP of file \fBstm32f4xx_it\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bus et Réseaux - VO from the source code\&.
