.TH "/home/oliver/Documents/3A/capteurs_reseaux_VO_ESE_TP2/capteurs_reseaux_VO/Core/Src/tim.c" 3 "Version TP5" "Bus et Réseaux - VO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/oliver/Documents/3A/capteurs_reseaux_VO_ESE_TP2/capteurs_reseaux_VO/Core/Src/tim.c \- This file provides code for the configuration of the TIM instances\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tim\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_TIM2_Init\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_TIM_Base_MspInit\fP (TIM_HandleTypeDef *tim_baseHandle)"
.br
.ti -1c
.RI "void \fBHAL_TIM_Base_MspDeInit\fP (TIM_HandleTypeDef *tim_baseHandle)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file provides code for the configuration of the TIM instances\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2024 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.PP
Definition in file \fBtim\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef * tim_baseHandle)"

.PP
Definition at line \fB90\fP of file \fBtim\&.c\fP\&.
.SS "void HAL_TIM_Base_MspInit (TIM_HandleTypeDef * tim_baseHandle)"

.PP
Definition at line \fB70\fP of file \fBtim\&.c\fP\&.
.SS "void MX_TIM2_Init (void)"

.PP
Definition at line \fB30\fP of file \fBtim\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "TIM_HandleTypeDef htim2"

.PP
Definition at line \fB27\fP of file \fBtim\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bus et Réseaux - VO from the source code\&.
